FilecoinFoundationWeb/filecoin-foundation-site

- _data/metadata.json
- _includes/layouts/base.njk
This PR just adds the GTM JS into the base template, as a quick and dirty implementation.
> Feat: Add Google Tag Manager for Analytics

- assets/scss/main.scss
- components/Card.vue
- content/pages/get-involved.json
- content/pages/grants.json
- content/pages/index.json
Card can now be turned into links in the same way as the `<Button>` component:
```js
{
"type": "A",
"action": "", // ← 'a' or 'nuxt-link'
"target": "", // ← '_blank'
"url": "", // ← The URL
"img": "",
"img_size": "",
"title": "",
"description": ""
}
```
> Feat: added links to some sections on Home, Grants and Get Involved pages

- components/Card.vue
- components/TextBlock.vue
- content/pages/get-involved.json
- nuxt.config.js
- package-lock.json
- package.json
**Requested Changes**
1. Content: add a link to the Lever job board on Careers page
2. Fix: one of the job postings was not correctly linked
3. Feat: remove dates from Careers Cards
> feat Jan21 requested changes

- nuxt.config.js
- package-lock.json
- package.json
Adds our matomo module npm package as a dependency with the relevant configs.
> feat: Added matomo config and dependency

- .forestry/front_matter/templates/data-open-graph-social.yml
- .forestry/front_matter/templates/data-seo.yml
- .forestry/front_matter/templates/page-general.yml
- content/pages/general.json
Made changes to `page-general.yml `to include fields descriptions and also added missing descriptions to `data-open-graph-social.yml `and `data-seo.yml`
> feat: additional metadata related field descriptions

- pages/_id.vue
- pages/blog.vue
A basic hover interaction added to blog post cards on the blog index & singular pages. The effect has been applied from above in the page components as opposed to within the card components to avoid affecting cards elsewhere in the site.
> style: Blog index & singular page card hover interaction

- content/pages/general.json
- nuxt.config.js
Redirect has been added to `nuxt.config.js`
> feat: redirect from `/filaustin` to `//events.bizzaboo.com/filaustin`

- README.md
- components/Navigation/NavDesktop.vue
Top level nav items triggering the dropdown menu on hover now link to their page as well as the headings in the dropdown.
> feat: Clickable top level nav items

- content/pages/about.json
Gary Moran updated content/pages/about.json
> Update from Forestry.io - supplemental

- content/data/event-list.json
- content/pages/get-involved.json
Gary Moran updated content/data/event-list.json
> Update from Forestry.io

- components/CardListBlock.vue
- content/pages/public-data-commons.json
- pages/public-data/index.vue
Adds conditions to the card list block which was coupled to render only if job postings where present. Non job postings card lists now ignore the job postings present condition.
> fix: missing card list blocks

- content/data/case-studies.json
- content/pages/public-data-awards.json
- package-lock.json
- package.json
Minor content updates prior to shipping new Public Data pages.
> content: minor pre-ship updates for PDC

- components/Accordion/accordion-content.vue
- components/Accordion/accordion-header.vue
- components/Accordion/accordion-section.vue
- components/Accordion/accordion.vue
- components/AccordionBlock.vue
- components/Breadcrumbs.vue
- components/Button.vue
- components/Navigation/NavDesktop.vue
- components/SiteFooter.vue
- components/SiteNavigation.vue
- content/pages/general.json
> feat: Tweaks and improvements

- components/Button.vue
- components/Card.vue
- components/FloatingMenu.vue
- components/SiteFooter.vue
- components/SliderBlock.vue
- components/TabbedSlider.vue
- components/VideoBlock.vue
- content/pages/about.json
- content/pages/ecosystem.json
- pages/grants.vue
Branch includes:
- accessibility polish for the governance, grants, about and ecosystem pages
> feat: accessibility fixes

- components/Card.vue
This PR provides a fix for cards in Advisors section on About page.
> fix: fixing image distortion

- components/Button.vue
- components/Card.vue
- components/CardListBlock.vue
- components/EventsHackathons.vue
- components/PaginatedCards.vue
- content/pages/blog.json
- content/pages/ecosystem.json
- content/pages/get-involved.json
- content/pages/governance.json
- content/pages/grants.json
- content/pages/index.json
- pages/_id.vue
- pages/basic-template-1.vue
- pages/blog.vue
- pages/filaustin.vue
- pages/governance.vue
- pages/grants.vue
- pages/public-data/index.vue
This PR addresses the following change requests:
**Homepage**
**About Page**
**Governance Page**
**Ecosystem Page**
**Grants Page**
**Get Involved Page**
**Blog Page**
**Blog Post Page**
> feat: fulfilling content change requests

- content/pages/about.json
- content/pages/basic-template-2.json
- content/pages/ecosystem.json
- content/pages/general.json
- content/pages/get-involved.json
- content/pages/governance.json
- content/pages/grants.json
- content/pages/index.json
- content/sections/dive-deeper.json
- nuxt.config.js
- pages/about.vue
- pages/basic-template-2.vue
- pages/ecosystem.vue
- pages/get-involved.vue
- pages/governance.vue
- pages/grants.vue
- pages/index.vue
This PR addresses Notion ticket `FIFO-34`. This PR renames sections throughout the Filecoin Foundation site, specifically pertaining to anchor tags. URLs are now more reflective of content that the user is seeing in the viewport.
> feat: rename sections

- pages/policy.vue
- static/policy.md
Replaces the old privacy policy (`/policy`) with entirely new content.
> content: new privacy policy

- .forestry/front_matter/templates/page-policy.yml
- content/employees.md
- content/pages/employees.json
- content/pages/general.json
- content/privacy-policy.md
- pages/employees.vue
Adds a new page for employee policy based on the privacy template
> feat: add new employee policy page

- content/blog/orbit-fvm-open-hack-days.md
Gary Moran updated content/blog/orbit-fvm-open-hack-days.md
> Blog Post Fix | Shenzhen spelling

- README.md
A test PR that triggers a rebuild. Although everything builds correctly locally, there seems to be some kind of an issue in the Fleek/IPFS workflow that's preventing normal builds.
It's also possible that one of the recent yml or md files might be causing an error that isn't being thrown in stdout.
> test: minor edit to trigger rebuild in CI
